### ISSUE TITLE
Not possible to change different numbers on same line.

### ISSUE THREAD

**Issue by mattiasbonte** [nat-418/boole.nvim#10]
Yo, 

I really enjoy using boole so thanks for creating something I didn't know I needed :). Today I've noticed something interesting though.

When <inc> or <dec> a number (for example `mb-10 ml-4 mr-2`) It automatically jumps to the `mb-10` word and <inc/dec> it. If I then move my cursor to `ml-4` it actually jumps back to `mb-10` and <inc/dec> that one again. This pattern repeats for other numbers in the same line.

Any thoughts on this? Is this behavior intended, or is this something which has not been noticed before? 

Keep up the good work. Cheers.

**Comment by nat-418** [comment]
That's a bug. I'll look into it. Thanks for the kind words and the report.

**Comment by mattiasbonte** [comment]
That's cool, thanks! 

Something else I've noticed. When for example changing `bg-blue-500` when my cursor is on the `5` it actually increases the `500` to `501`. Same happens when cursor is on the first 5`0`0. Is that intended? 

Imho it would make sense to only inc/dec the number targeted by the cursor or selection?

**Comment by mattiasbonte** [comment]
Just to inform but this behavior is still present even after the merge.
It happens whenever I am inside a className tag. For example.

`<div className="my-2 mb-10 bg-blue-500">`

When incrementing it will auto jump to `my-2` and increment it to `my-3`, but there i no way to target `mb-10` or `bg-blue-500` since it auto jumps to `my-2`

**Comment by nat-418** [comment]
Thanks for reporting this. I think I finally got the bug, but I will leave this issue open for you to close when you have time to pull the latest version and test it yourself.

**Comment by mattiasbonte** [comment]
Looks perfect! Thanks. Not sure if I can close though, the button is gone now.
