### ISSUE TITLE
modified value not placed correctly if prepended with whitespaces and special characters only

### ISSUE THREAD

**Issue by rkmiec** [nat-418/boole.nvim#13]
If there is a word to increment/decrement after some whitespace characters and the cursor is not directly on the word, then incremented/decremented word is misplaced.
Example (cursor is always on the first column):
```
test february <- not incremented until cursors moves to february
    february <- incremented but inserted in front of february instead of whitespace characters
    {{{)()((''' february <- incremented, but replaces first whitespace
    something february <- not incremented
```

**Comment by nat-418** [comment]
Thanks for the report. I will try and get a bugfix out soon.

**Comment by nat-418** [comment]
I've reworked the code to handle these cases. I am still not sure how to deal with things like 'true' vs true or false) vs false. For now I have taken the more conservative approach of excluding them from matches. Please let me know @rkmiec  what you think.

**Comment by rkmiec** [comment]
The bug is now fixed. I have also noticed that the cursor after incrementing no longer goes to the end of the word, which is a good thing. Great work and thanks for fixing it so quickly.
