### ISSUE TITLE
Not triggering boole when in middle of the word.

### ISSUE THREAD

**Issue by mattiasbonte** [nat-418/boole.nvim#18]
Hi,

Something small I've noticed lately. When I am standing on the (for example) `a` of `false` and inc or decr boole, it doesn't do anything.
When there is another true / false after it on the same line, then it will jump to the next one and toggle it. 
When I stand on the first letter of the word however, then the behavior works as intended.

Wouldn't it make sense when the cursor is inside the word itself that it changes the actual word. instead of jumping to the next match?

Cheers.

**Comment by nat-418** [comment]
thanks for the bug report and comments. I am working on this now.

**Comment by mattiasbonte** [comment]
It works! Thanks a lot 💪🏼
