### ISSUE TITLE
Number increase strange behavior

### ISSUE THREAD

**Issue by Benson9954029** [nat-418/boole.nvim#20]
![without_plugin](https://user-images.githubusercontent.com/28132352/210734208-96fc1d63-be45-4451-a010-51bab7f00b3a.gif)
![with_plugin](https://user-images.githubusercontent.com/28132352/210734225-9e4a414a-05f3-4a47-afb9-54106b27f99f.gif)
Example 1:
_ 1test true  `(2<C-a>)`
Expected behavior
<ins>3</ins>test true
Actual behavior
1test <ins>f</ins>alse     (ignore the number)
Example 2:
<ins>t</ins>est  12 `(10 <C-a>)`
Expected behavior
test 2<ins>2</ins> 
Actual behavior
test 1<ins>3</ins>      (ignore the count)

**Comment by nat-418** [comment]
Please test the latest main branch and close this issue if those changes resolve your issue.

**Comment by Benson9954029** [comment]
Thanks for quickly response.
It's works well for me.
