### ISSUE TITLE
Does not find first occurance of (inc/dec)rementable

### ISSUE THREAD

**Issue by gimerstedt** [nat-418/boole.nvim#4]
Without the plugin c-a and c-x both move the cursor to the first occurance of a number on the line and inc/dec it. Is this a planned feature?

**Comment by gimerstedt** [comment]
removing the type checks solves this:
https://github.com/nat-418/boole.nvim/blob/main/lua/boole.lua#L291
https://github.com/nat-418/boole.nvim/blob/main/lua/boole.lua#L297

not sure if it adds some unwanted behavior.

**Comment by nat-418** [comment]
Very interesting, I never noticed that behavior before.

**Comment by gimerstedt** [comment]
cheers!
